// src/components/layout/Navbar.tsx
"use client";

import Link from "next/link";
import { useSession, signOut } from "next-auth/react";
import { Button } from "@/components/ui/button";
import { ThemeToggle } from "@/components/ThemeToggle";
import { BookOpen, LogOut, LayoutDashboard } from "lucide-react";

export function Navbar() {
  const { data: session } = useSession();

  return (
    <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/80 backdrop-blur-md supports-[backdrop-filter]:bg-background/60 shadow-sm transition-all duration-300">
      <div className="container flex h-16 items-center justify-between mx-auto px-4 md:px-8">
        <div className="flex items-center gap-4">
          <Link href="/" className="flex items-center space-x-2 group">
            <div className="bg-primary/10 p-2 rounded-lg group-hover:bg-primary/20 transition-colors">
              <BookOpen className="h-5 w-5 text-primary" />
            </div>
            <span className="font-bold inline-block text-primary text-xl tracking-tight hidden sm:inline-block">Reposituri STIESNU</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6 ml-6 text-sm font-medium">
            <Link href="/" className="transition-colors hover:text-foreground/80 text-foreground/60">Beranda</Link>
            <Link href="/repository" className="transition-colors hover:text-foreground/80 text-foreground/60">Koleksi</Link>
          </nav>
        </div>

        <div className="flex items-center gap-4">
          <ThemeToggle />
          
          {session ? (
            <div className="flex items-center gap-3">
              {(session.user.role === "ADMIN" || session.user.role === "DOSEN") && (
                <Button variant="outline" size="sm" asChild>
                  <Link href="/dashboard">
                    <LayoutDashboard className="h-4 w-4 mr-2" />
                    Dashboard
                  </Link>
                </Button>
              )}
              <div className="hidden md:flex flex-col items-end text-xs">
                <span className="font-medium">{session.user.name}</span>
                <span className="text-muted-foreground">{session.user.role}</span>
              </div>
              <Button variant="ghost" size="icon" onClick={() => signOut()}>
                <LogOut className="h-4 w-4 text-destructive" />
              </Button>
            </div>
          ) : (
            <div className="flex items-center gap-2">
              <Button variant="ghost" size="sm" asChild>
                <Link href="/login">Masuk</Link>
              </Button>
              {/* Optional: Add register link if public registration is needed */}
            </div>
          )}
        </div>
      </div>
    </header>
  );
}

// frontend-vue/src/components/layout/Navbar.vue
<template>
  <header class="sticky top-0 z-50 w-full border-b border-gray-200/40 bg-white/80 backdrop-blur-md supports-[backdrop-filter]:bg-white/60 shadow-sm transition-all duration-300">
    <div class="container flex h-16 items-center justify-between mx-auto px-4 md:px-8">
      <div class="flex items-center gap-4">
        <router-link to="/" class="flex items-center space-x-2 group">
          <div class="bg-emerald-600/10 p-2 rounded-lg group-hover:bg-emerald-600/20 transition-colors">
            <PhBookOpen :size="20" weight="bold" class="text-emerald-600" />
          </div>
          <span class="font-bold inline-block text-emerald-700 text-xl tracking-tight hidden sm:inline-block">
            Reposituri STIESNU
          </span>
        </router-link>
        <nav class="hidden md:flex items-center gap-6 ml-6 text-sm font-medium">
          <router-link to="/" class="transition-colors hover:text-gray-900/80 text-gray-600">Beranda</router-link>
          <router-link to="/repository" class="transition-colors hover:text-gray-900/80 text-gray-600">Koleksi</router-link>
        </nav>
      </div>

      <div class="flex items-center gap-4">
        <!-- Optional Theme Toggle here -->
        
        <div v-if="authStore.isAuthenticated && authStore.user" class="flex items-center gap-3">
          <Button 
            variant="outline" 
            size="sm" 
            @click="router.push('/dashboard')"
          >
            <PhLayout :size="16" class="mr-2" />
            Dashboard
          </Button>
          
          <div class="hidden md:flex flex-col items-end text-xs">
            <span class="font-medium">{{ authStore.user.name }}</span>
            <span class="text-gray-500">{{ authStore.user.role }}</span>
          </div>
          
          <Button variant="ghost" size="icon" @click="logoutAlertOpen = true">
            <PhSignOut :size="16" class="text-red-500" />
          </Button>
        </div>
        
        <div v-else class="flex items-center gap-2">
          <Button variant="ghost" size="sm" @click="router.push('/login')">
            Masuk
          </Button>
          <Button variant="default" size="sm" @click="router.push('/register')" class="hidden sm:inline-flex">
            Daftar
          </Button>
        </div>
      </div>
    </div>

  </header>

  <!-- Modal Konfirmasi Logout -->
  <div v-if="logoutAlertOpen" class="fixed inset-0 z-[110] bg-black/50 backdrop-blur-sm flex items-center justify-center p-4">
    <div class="bg-white rounded-lg shadow-lg w-full max-w-sm overflow-hidden animate-fade-in-up">
      <div class="p-6">
        <h2 class="text-lg font-bold text-gray-900">Konfirmasi Keluar</h2>
        <p class="text-gray-500 mt-2">
          Apakah Anda yakin ingin keluar dari akun Anda?
        </p>
      </div>
      <div class="px-6 py-4 bg-gray-50 flex items-center justify-end gap-3 border-t border-gray-100">
        <Button variant="outline" @click="logoutAlertOpen = false">Batal</Button>
        <Button class="bg-red-600 hover:bg-red-700 text-white" @click="handleLogoutConfirm">Ya, Keluar</Button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../../stores/auth'
import Button from '../ui/Button.vue'
import { PhBookOpen, PhLayout, PhSignOut } from '@phosphor-icons/vue'

const router = useRouter()
const authStore = useAuthStore()

const logoutAlertOpen = ref(false)

const handleLogoutConfirm = async () => {
  logoutAlertOpen.value = false
  await authStore.logout()
  router.push('/')
}
</script>

<style scoped>
@keyframes fadeInUp {
  from { opacity: 0; transform: translateY(10px); }
  to { opacity: 1; transform: translateY(0); }
}
.animate-fade-in-up {
  animation: fadeInUp 0.2s ease-out forwards;
}
</style>
